trigger:
- None

name: '1.0.$(Build.BuildId)'

variables:
- name: androidKeystoreKeyAlias
  value: key

jobs:
- job: BuildAndroid
  displayName: Build for Android
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: FlutterInstall@0
    displayName: Install Flutter
    inputs:
      channel: 'beta'
      version: 'latest'
  - task: FlutterBuild@0
    displayName: Build App
    inputs:
      target: 'apk'
      projectDirectory: '.'
      buildName: '$(Build.BuildNumber)'
  - task: PublishBuildArtifacts@1
    displayName: Publish artifact
    inputs:
      PathtoPublish: '$(Build.Repository.LocalPath)/build/app/outputs/apk/release'
      ArtifactName: 'apk'
      publishLocation: 'Container'
