trigger:
- None

name: '1.0.$(Build.BuildId)'

variables:
- name: androidKeystoreKeyAlias
  value: key

jobs:
- job: BuildAndroid
  displayName: Build for Android
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: CmdLine@2
    inputs:
      script: 'ls'
  - task: FlutterBuild@0
    inputs:
      target: 'apk'
      projectDirectory: '\home\vsts\work\_temp\'
      debugMode: true
      buildFlavour: 'dev'
      buildName: '$(Build.BuildNumber)'
  - task: PublishBuildArtifacts@1
    displayName: Publish artifact
    inputs:
      PathtoPublish: '$(Build.Repository.LocalPath)/build/app/outputs/apk/release'
      ArtifactName: 'apk'
      publishLocation: 'Container'
